---
Name: appconfig
---
ilateral\SilverStripe\Searchable\Searchable:
  objects:
    "Page": ["Title","MenuTitle","Content","URLSegment"]
    "Product": ["Title","Content","URLSegment"]
    "Category": ["Title","Content","URLSegment"]

ilateral\SilverStripe\CustomMenus\Model\CustomMenuLink:
  base_classes:
    "Category": "A Product Category"
    "Product": "A Product"

ilateral\SilverStripe\Users\Users:
  require_verification: false
  send_verification_email: false
